### PR TITLE
Always add alternative layers to trees and rocks

### LINKED ISSUE #21: Slight incompatibility with Space Explorations Constrcution Pylons
Space Exploration has an item called Constrcution Pylon and Radar Constrcution Pylon. These are basically a roboprt and a power pole at once. If you blueprint a single one, then the blueprint actually shows, that it requires two of them. Without #20 only one of them has a dummy. With that PR both have a dummy.  
Issue happens in both versions. Everything works fine when placed on land. But when placed on water, it will break, because robots will place at least one of the ghost. If that happens before the landfill is placed, then it will stay forever a dummy item and the other ghost will also stay there forever.  
Probably happens with every multi-entity (or however the technical term is for these).

### PR DESCRIPTION
**Pull request by ChaosSaber**
Fixes #21 and #30

### CODE REVIEW

**Comment by KeinNiemand** [comment]
I'll test and merge this when I have the time.

**Comment by KeinNiemand** [comment]
don't seem to work, the layers get added, but rail signals still don't collide with trees/rocks, pylons don't work (due to not colliding with item layer), and items on ground still don't get marekd for deconstruction, maybe that just not how items on ground works, since after testing even normal entities can be placed on top of itmes laying on the ground without them beeing marked for deconstruction, the  bots just build stuff over items on the ground, so no reason to collide with items in the first place.

**Comment by ChaosSaber** [comment]
Yes, the rail signal and chain signals are not handled by the addAlternativeLayerForSpeicalRemovals function. Did not yet look into why.  
The issue with the space placeable entities from SE is, that these are missing the item-layer. I opened a bug report on their side to add them, as they seem to be not present because of older limitations, when there were fewer collision layers. It was not addressed with the patch yesterday, so I asked them if it will be fixed and the answer was probably yes, but the priority is very low for a change with rather high risk.  
Therefore I will commit my workaround which I am currently using.

**Comment by KeinNiemand** [comment]
No idea why addAlternativeLayerForSpeicalRemovals isn't dosn't affect rail singals, it should handle all entitys, do have you checked if signals collide with item layer of floor layer in the first place, It should go over all entries in the game so I've no idea why rail signals don't work.

**Comment by ChaosSaber** [comment]
I stand corrected. They are handled by that function.  That believe probably stems from before I realised that more entities are missing the item-layer in SE and at that time the signals where not handled, because they didn't fit the filter criteria. But since I later added floor-layer as a workaround they were working.

**Comment by KeinNiemand** [comment]
In that case, floor-layer (or one of the other layers both rail singals and pylons collide with) should be the default layer especially since adding the item layer dosn't do anything for items on the ground. Maybe look into one of the other layers to see if any of them already collide with trees/rocks so the workaround of always adding the layer to trees/rocks is no longer necessary, which is a bit of an ugly workaround, what if some mod has trees/rocks that do collide with some things but explicitly shouldn't collide with floor layer stuff, those then shouldn't get the extra layer, I doubt that there actually is any mod that does that but better stay as theoretically compatible as possible.

**Comment by ChaosSaber** [comment]
I have chosen the following special removal layers: "item-layer", "floor-layer", "object-layer" and "water-tile", without forcibly adding them to trees/rocks for the following reasons:  
The following collision masks are present:  
rail/chain signals: "floor-layer", "item-layer", "rail-layer" / "floor-layer", "rail-layer", "water-tile" with SE  
trees/rocks: "item-layer", "object-layer", "player-layer", "water-tile"  
SE Pylons: "floor-layer", "player-layer", "water-tile"  
Sadly no layer is present in all of them. I have choosen the item-layer because it is present in most entities and should be present in the SE entities. Only the following relevant entities do not have the item-layer: heat pipe, land mine and transport belt. Because even in vanilla land mines have no common collision layer with rail/chain signals I will ignore them. The remaining have in common the water-tile, object-layer and floor layer.  
Which means without alien biomes or SE the item-layer as special removal layer is enough and covers all special cases.  
With alien biomes the floor-layer is also removed. Which leads to rail/chain signals, heat pipes and transport belts no longer having a common collision layer. Therefore we need the floor-layer as special removal layer. We don't have to add the floor-layer to trees and rocks, because they are colliding already with other layers.  
With SE the object-layer is now also removed, which is needed for most collisions. As far as i can see every entity with the object-layer also has water-tile. Which means we could use them interchangeably. Because SE adds some entities which can be placed in space (no object-layer) but cannot be placed on water (water-tile), I have added the water-tile to the special removal layers.  
Since i know, that there are some mods out there which add rails on water, I looked up their collision masks, which was the opposite to the SE space entities. (They had the object-layer, but not water-tile). Which means that we unfortunately need both layers as special removal layers. At least until SE added the item-layer to their entities.  
  
As for the item-on-gound entity: You are right. This does not change anything in this aspect. I was under the impression that items on the gound are marked for pickup/deconstruction when placing a ghost over it. But they are actually picked up when placing the entity over it (as long as said entity has the item-layer collision). Don't know why i thought like that, especially since i did some tests at the beginning regarding dropped items. But that would need to be fixed somewhere else. Whereever the check happens if a dummy ghost should be replaced with the actual ghost.

**Comment by KeinNiemand** [comment]
> As for the item-on-gound entity: You are right. This does not change anything in this aspect. I was under the impression that items on the gound are marked for pickup/deconstruction when placing a ghost over it. But they are actually picked up when placing the entity over it (as long as said entity has the item-layer collision). Don't know why i thought like that, especially since i did some tests at the beginning regarding dropped items. But that would need to be fixed somewhere else. Whereever the check happens if a dummy ghost should be replaced with the actual ghost.

I was under the same impression, the only way I can think of to actually solve the item problem would be to activly search for items under water ghosts and remove them but that would require using find_entities_filtered which is pretty slow performance wise so it's probably not worth doing over such a minor issue (it's pretty easy to just use a decon planer) I'll test this PR again as soon as I've got the time.

**Pull request merged**
