### PR TITLE
remove valid crafting categories from the dummy entities.

### PR DESCRIPTION
**Pull request by nekizalb**
this will prevent planning mods from considering the dummy machines

### CODE REVIEW

**Comment by nekizalb** [comment]
Hello. This is an attempt at fixing the issue I reported here: https://mods.factorio.com/mod/GhostOnWater/discussion/639e8cb611f3609bf9fa582b

The goal was to make the dummy entities invisible to factory planning mods such as Factory Planner. This accomplishes that goal by removing all valid crafting categories from the copied machines, such that they no longer have any valid recipes they can complete. This successfully hid the machines from Factory Planner's interface. 

Please let me know if i did not follow a convention accurately. I have no modded factorio before...

**Review by KeinNiemand — CHANGES_REQUESTED** [review]
Not every entity has a crafting category, only crafting machines have one (assembly machines for example) so there'd need to be a check to check if crafting category is set at all. Tough it seems like the game probably just ignores the crafting category fo entitys that dont have one.
Also constants.dummyPrefix should probably be used for the name of the category rather then just dummy since dummy is to generic and might be used by other mods.
Also this crashes the game becouse categorys.lua dosn't get loaded, there needs to be a require in data.lua tough I have done that.

**Comment by nekizalb** [comment]
I will make the requested changes. The game loaded ok with the crafting
category set on everything, but I think you're right it should check, just
in case.

Not loading the file was a dumb mistake. When I first tested, I had it in
one of the existing files. I thought I ran the game again after moving to a
new one, but obviously not.

Thanks for the feedback and consideration. Will have a new push soon

**Comment by nekizalb** [comment]
Ok, should be aligned to your requests. I initially wasn't sure whether the dash in the prefix would be an issue, but the game seems to have accepted it just fine. I was able to place ghosts on water for both crafters and non crafters, and Factory Planner still doesn't show the dummies as available for use.

**Pull request merged**
